# Site settings
title: "PyTorch Website"
author: "Facebook"
default_author: The PyTorch Team
description: "Scientific Computing..."
latest_version: 1.0
timezone: America/Los_Angeles
url: "https://pytorch.org"
baseurl: ""
plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-autoprefixer
  - jekyll-feed
sass:
  load_paths:
    - _sass
    - node_modules
exclude: [vendor, node_modules, README.md, Gemfile, Gemdile.lock, yarn.lock, yarn-error.log, package.json, Makefile, scripts, _hub/docs/template.md]
include: [_static, _images, _modules, _sources, _tensor_str.html, _utils.html]
keep_files: [vendor/assets, docs/master/_static/js/vendor/]
github: [metadata]
external_urls:
  github: https://github.com/pytorch/pytorch
  github_issues: https://github.com/pytorch/pytorch/issues
  hub_issues: https://github.com/pytorch/hub/issues
  contributing: https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md
  twitter: https://twitter.com/pytorch
  facebook: https://www.facebook.com/pytorch
  slack: https://goo.gl/forms/PP1AGvNHpSaJP8to1
  discuss: https://discuss.pytorch.org
  tutorials: https://pytorch.org/tutorials
  previous_pytorch_versions: https://pytorch.org/previous-versions/
  udacity_courses: https://pytorch.org
livereload: true
markdown: kramdown
highlighter: rouge
collections:
  get_started:
    output: true
  ecosystem:
    output: true
    permalink: /ecosystem/:path/
  hub:
    output: true
    permalink: /hub/:title/
  case_studies:
    output: true
    permalink: /case-studies/:path/
  style_guide:
    output: false
  posts:
    output: true
    permalink: /blog/:title/
  resources:
    output: false
  features:
    output: false
  courses:
    output: false

pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# google_site_verification: eOAFtDphTbbm4OPKva2d3Z0Z_2bBxWMGdkD0IRQ6VeA
