# Site settings
title: "PyTorch Website"
author: "Facebook"
default_author: Team PyTorch
description: "Scientific Computing..."
latest_version: 1.0
timezone: America/Los_Angeles
url: "https://pytorch.org"
baseurl: ""
plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-autoprefixer
  - jekyll-feed
sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  [
    vendor,
    node_modules,
    README.md,
    Gemfile,
    Gemdile.lock,
    yarn.lock,
    yarn-error.log,
    package.json,
    Makefile,
    scripts,
    _hub/docs/template.md,
  ]
include:
  [
    _static,
    _images,
    _modules,
    _sources,
    _asserts.html,
    _comparison.html,
    _creation.html,
    _dynamo.html,
    _inductor.html,
    _lowrank.html,
    _script.html,
    _serialization.html,
    _symbolic_trace.html,
    _tensor_str.html,
    _trace.html,
    _utils.html,    
  ]
keep_files: [vendor/assets, docs/master/_static/js/vendor/]
github: [metadata]
external_urls:
  github: https://github.com/pytorch/pytorch
  github_issues: https://github.com/pytorch/pytorch/issues
  hub_issues: https://github.com/pytorch/hub/issues
  contributing: https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md
  hub_template: https://github.com/pytorch/hub/blob/master/docs/template.md
  twitter: https://twitter.com/pytorch
  facebook: https://www.facebook.com/pytorch
  slack: https://goo.gl/forms/PP1AGvNHpSaJP8to1
  discuss: https://discuss.pytorch.org
  contributor_forum: https://dev-discuss.pytorch.org/
  tutorials: https://pytorch.org/tutorials
  previous_pytorch_versions: https://pytorch.org/previous-versions/
  udacity_courses: https://pytorch.org
  security: https://github.com/pytorch/pytorch/security/policy
  youtube: https://www.youtube.com/pytorch
  spotify: https://open.spotify.com/show/6UzHKeiy368jKfQMKKvJY5
  apple: https://podcasts.apple.com/us/podcast/pytorch-developer-podcast/id1566080008
  google: https://www.google.com/podcasts?feed=aHR0cHM6Ly9mZWVkcy5zaW1wbGVjYXN0LmNvbS9PQjVGa0lsOA%3D%3D
  amazon: https://music.amazon.com/podcasts/7a4e6f0e-26c2-49e9-a478-41bd244197d0/PyTorch-Developer-Podcast?
  linkedIn: https://www.linkedin.com/company/pytorch
  mastodon: https://social.lfx.dev/@pytorch
livereload: true
markdown: kramdown
highlighter: rouge
collections:
  get_started:
    output: true
  ecosystem:
    output: true
    permalink: /ecosystem/:path/
  hub:
    output: true
    permalink: /hub/:title/
  community_stories:
    output: true
    permalink: /community-stories/:path/
  style_guide:
    output: false
  posts:
    output: true
    permalink: /blog/:title/
  resources:
    output: false
  features:
    output: false
  courses:
    output: false
  mobile:
    output: true
  news:
    output: true
  past_issues:
    output: true
  events:
    output: true
    future: true
  case_studies:
    output: true
  board_info:
    output: true
  community_blog:
    output: true
  videos:
    output: true

pagination:
  enabled: true
  per_page: 8
  permalink: "/:num/"
  title: ":title | :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2
# google_site_verification: eOAFtDphTbbm4OPKva2d3Z0Z_2bBxWMGdkD0IRQ6VeA
