name: Check install matrix
on:
  push:
    branches:
      - site
    paths:
      - assets/quick-start-module.js
      - _includes/quick-start-module.js
      - published_versions.json
      - scripts/**
      - .github/**
  pull_request:
    paths:
      - assets/quick-start-module.js
      - _includes/quick-start-module.js
      - published_versions.json
      - scripts/**
      - .github/**

jobs:
  check-regen:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout Pytorch.github.io
        uses: actions/checkout@v2
      - name: Regen quick-start-module
        run: |
          python3 scripts/gen_quick_start_module.py >assets/quick-start-module.js
          CHANGES=$(git status --porcelain "assets/quick-start-module.js")
          echo "$CHANGES"
          [ -z "$CHANGES" ]

  libtorch-downloadable:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout Pytorch.github.io
        uses: actions/checkout@v2
      - name: Attempt to download libtorch
        run: |
          python3 scripts/test_libtorch_downloadable.py

  pip-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rel_type: [ "latest_stable", "latest_lts" ]
        acc_type: [ "cuda11.x", "cuda10.2", "accnone" ]
        py_vers: [ "3.7", "3.8", "3.9" ]
        os: ["ubuntu-18.04", "macos-latest", "windows.4xlarge"]
    env:
      TEST_ACC: ${{ matrix.acc_type }}
      TEST_VER: ${{ matrix.rel_type }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py_vers }}
          architecture: x64
      - name: Checkout Pytorch.github.io
        uses: actions/checkout@v2
      - name: Test pip3 install
        run: |
          python3 scripts/test_install.py
        if: runner.os != 'Windows'
      - name: Test pip3 install on Windows
        shell: powershell
        run: |
          $env:PATH+=';'+$env:pythonLocation
          python3.exe scripts/test_install.py
        if: runner.os == 'Windows'

  conda-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rel_type: [ "latest_stable" ]
        acc_type: [ "cuda11.x", "cuda10.2", "accnone" ]
        py_vers: [ "3.7", "3.8", "3.9" ]
        os: ["ubuntu-18.04", "macos-latest"]
    env:
      TEST_ACC: ${{ matrix.acc_type }}
      TEST_VER: ${{ matrix.rel_type }}
    steps:
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.py_vers }}
          architecture: x64
      - name: Checkout Pytorch.github.io
        uses: actions/checkout@v2
      - name: Test conda install
        shell: bash -l {0}
        run: |
          python3 scripts/test_install.py --conda
